import type { OptimizerOptions, OptimizerWeights, PrimitiveLossType } from "./types";

export const DEFAULT_OPTIMIZER_WEIGHTS: OptimizerWeights = {
  userSoftKeyframe: 40,
  semanticPrimary: 10,
  semanticStabilizer: 2.5,
  globalSmoothness: 2,
  globalAngularSmoothness: 1,
  globalJerk: 0.4,
  globalCollision: 18,
  globalOcclusion: 5,
  globalGround: 12,
  globalMinPath: 0.025,
};

export const DEFAULT_GLOBAL_LOSSES = {
  smoothness: true,
  angularSmoothness: true,
  jerk: true,
  collision: true,
  occlusion: true,
  ground: true,
  minPath: true,
} as const;

export const DEFAULT_OPTIONS: Required<Omit<OptimizerOptions, "weights" | "globalLosses">> = {
  optimizationFps: 3,
  outputFps: 24,
  iterations: 5000,
  randomSeed: 0x51f15e,
  initialFovYDegrees: 50,
  aspectRatio: 16 / 9,
  cameraRadius: 0.18,
  collisionMargin: 0.12,
  nearPlane: 0.05,
  farPlane: 1000,
};

/** Default tolerances define acceptable error, not importance. */
export const PRIMITIVE_TOLERANCES: Record<PrimitiveLossType, number> = {
  positionAnchor: 0.03,
  rotationAnchor: Math.PI / 180,
  fovAnchor: 0.5,
  positionHold: 0.04,
  orientationHold: Math.PI / 180,
  forwardHold: Math.PI / 180,
  yawHold: Math.PI / 180,
  pitchHold: Math.PI / 180,
  rollHold: Math.PI / 180,
  fovHold: 0.5,
  axisProgress: 0.05,
  totalProgressTarget: 0.08,
  orthogonalDrift: 0.06,
  pathProfile: 0.08,
  stepPacing: 0.15,
  stepSmoothness: 0.15,
  angularProgress: Math.PI / 90,
  angularDirection: Math.PI / 90,
  angularPacing: Math.PI / 45,
  planeHold: 0.06,
  radiusHold: 0.08,
  radiusSchedule: 0.08,
  lookAt: Math.PI / 180,
  screenPosition: 0.025,
  bboxInFrame: 0.02,
  screenScale: 0.035,
  distanceHold: 0.08,
  relativeOffsetHold: 0.08,
  bearingHold: Math.PI / 90,
  elevationHold: Math.PI / 90,
  velocityMatch: 0.12,
  subjectView: Math.PI / 60,
  subjectElevation: Math.PI / 60,
  rollProgress: Math.PI / 90,
  rollTarget: Math.PI / 90,
  levelHorizon: Math.PI / 90,
  intrinsicsProgress: 0.75,
  intrinsicsPacing: 0.75,
  collisionClearance: 0.05,
  nearPlaneClearance: 0.02,
  occlusion: 0.05,
  heightAboveGround: 0.06,
  groundClearance: 0.05,
  accelerationSmoothness: 0.35,
  angularAccelerationSmoothness: 0.3,
  jerkSmoothness: 0.8,
  pathLength: 1,
};
